config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :works
  default_url_options :host => "tradesgram.com"

  resources :projects
  
  resources :questions do
    resources :answers
  end
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:show]

  get 'pages/search_result'
  get 'pages/index'

  authenticated :user do
    root 'pages#index', as: :authenticated_root
  end
  root 'pages#landing'

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/models/project.rb
class Project < ActiveRecord::Base
	mount_uploader :portfolio, PortfolioUploader
	belongs_to :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.projects
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = current_user.projects.build
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.build(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :city, :deadline, :active)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'Full'} } %>
    <%= f.input :city %>
    <%= f.input :deadline %>
    <%= f.input :active %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h2>Edit Project</h2>
		<hr>
		<%= render 'form' %>
		<%= link_to 'Cancel', projects_path, class: "btn btn-link" %>
	</div><!-- end col-md-6 -->
</div>

app/views/projects/index.html.erb
<div class="row">
  <div class="col-md-12">
    <h2>My Projects 
      <%= link_to new_project_path, class: "btn btn-success btn-xs" do %>
        <i class="fa fa-plus" aria-hidden="true"></i> Add New Project
      <% end %>
    </h2>
    <hr>
    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>City</th>
          <th>Deadline</th>
          <th>Active</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @projects.each do |project| %>
          <tr>
            <td><%= project.name %></td>
            <td><%= project.description %></td>
            <td><%= project.city %></td>
            <td><%= project.deadline %></td>
            <td><%= project.active %></td>
            <td>
              <%= link_to project do %>
                <i class="fa fa-eye" aria-hidden="true"></i> Show
              <% end %>
            </td>
            <td>
              <%= link_to edit_project_path(project) do %>
                <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Edit
              <% end %>
            </td>
            <td>
              <%= link_to project, method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i class="fa fa-trash-o" aria-hidden="true"></i> Delete
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  
</div><!-- end row -->

app/views/projects/new.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<h2>New Project</h2>
		<hr>
		<%= render 'form' %>
		<%= link_to 'Cancel', projects_path, class: "btn btn-link" %>
	</div><!-- end col-md-6 -->
</div>

app/views/projects/show.html.erb
<div class="row">
  <div class="col-md-9">
    <h2><%= @project.name %></h2>
    <hr>
    <small>Project posted <%= time_ago_in_words(@project.created_at) %> ago by <%= @project.user.full_name %> </small>
    <br><br>
    <h4><%= @project.description %></h4>
    <hr>
    <h5>Location: <%= @project.city %></h5>
    <h5>Deadline: <%= @project.deadline.strftime("%b %d, %Y") %></h5>
    
  </div><!-- end col-md-9 -->
  <div class="col-md-3">
    <h2>Interested?</h2>
    <hr>
    <%= link_to new_conversation_path, class: "btn btn-success btn-lg" do %>
      <i class="fa fa-envelope-o" aria-hidden="true"></i> <%= @project.user.full_name %>
    <% end %>
  </div>
</div><!-- end row -->