config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  resources :works
  default_url_options :host => "tradesgram.com"

  resources :projects
  
  resources :questions do
    resources :answers
  end
  
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users, only: [:show]

  get 'pages/search_result'
  get 'pages/index'

  authenticated :user do
    root 'pages#index', as: :authenticated_root
  end
  root 'pages#landing'

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

end

app/views/layouts/_alert.html.erb
<div class="alert text-center 
    <%= 
    case type.to_sym 
    when :alert, :danger, :error, :validation_errors
        'alert-danger'
    when :warning, :todo
        'alert-warning'
    when :notice, :success
        'alert-success'
    else 
        'alert-info'
    end
    %>
     alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
    <%= content %>
</div>

app/views/layouts/_footer.html.erb
<footer style="background-color: #ececec; color: #737373; padding-top: 30px; padding-bottom: 30px; margin-top: 77px;">
	<div class="container">
	  <div class="row">
	    <div class="col-md-4">
	    	<h3>Tradesgram</h3>
	    	<hr>
	    	<p><i class="fa fa-map-marker" aria-hidden="true"></i> 20069 2nd Ave SW<br>
	    		Seattle, WA</p>
	    	<p><i class="fa fa-phone" aria-hidden="true"></i> +1 206-327-3148</p>
	    </div><!-- end col-md-4 -->
	    <div class="col-md-4">
	    	<h3>Follow Us</h3>
	    	<hr>
	    	<p><a href="https://www.facebook.com/Tradesgram-472834876234190/" target="_blank"><i class="fa fa-facebook-official" aria-hidden="true" style="color: #3b5998; font-size: 3em;"></i></a> <a href="https://twitter.com/tradesgram" target="_blank"><i class="fa fa-twitter-square" aria-hidden="true" style="color: #55acee; font-size: 3em;"></i></a>
	    </div><!-- end col-md-4 -->
	    <div class="col-md-4">
	    	<h3>Our Sponsors</h3>
	    	<hr>
	    	
	    </div><!-- end col-md-4 -->
	  </div><!-- end row -->
	</div><!-- end container -->

</footer>

<footer style="color: black; padding-top: 10px; padding-bottom: 10px;">
	<div class="container">
	  <div class="row">
	    <div class="col-md-8">
	    	<p>Copyright © 2016 Tradesgram. All Rights Reserved.
	    </div><!-- end col-md-4 -->
	    <div class="col-md-4" style="float: right;">
	    	<p>Privacy Policy | Terms &amp; Conditions</p>
	    </div><!-- end col-md-4 -->
	  </div><!-- end row -->
	</div><!-- end container -->

</footer>

app/views/layouts/_non_user_nav.html.erb
<nav class="navbar navbar-default" style="background-color: white;">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand", style: "margin-top: -10px;" do %>
        <%= image_tag "http://res.cloudinary.com/handyguyz/image/upload/c_scale,w_200/v1481182061/logo-rex_wuqp4o.png", class: "img-responsive" %>
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to('Login', new_user_session_path, style: "color: #2c3e50;") %></li>
    	<li><%= link_to('Register', new_user_registration_path, style: "color: #2c3e50;") %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_registered_user_nav.html.erb
<nav class="navbar navbar-default" style="background-color: white;">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand", style: "margin-top: -10px;" do %>
        <%= image_tag "http://res.cloudinary.com/handyguyz/image/upload/c_scale,w_200/v1481182061/logo-rex_wuqp4o.png", class: "img-responsive" %>
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      </ul>
      <%= form_tag(pages_search_result_path, :method => "get", id: "search-form", class: "navbar-form navbar-left", role: "search") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Tradesgram", class: "form-control" %>
          <%= submit_tag "Search", :name => nil, class: "btn btn-default" %>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
      	<li>
        	<%= link_to new_question_path, style: "color: #2c3e50;" do %>
        		<i class="fa fa-plus" aria-hidden="true"></i> Ask Tradesgram
        	<% end %>
        </li>
        <li>
          <%= link_to mailbox_inbox_path do  %>
              <span class="label label-danger pull-right" style="margin-left:5px;"> <%=unread_messages_count%></span>
              <em class="fa fa-inbox fa-lg" style="color: #2c3e50;"></em>
              <span style="color: #2c3e50;">Messages</span>
          <% end %>
        </li>
        <li class="dropdown">
          <a href="#" style="color: #2c3e50;" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Hello, <%= current_user.full_name %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "My Public Profile", current_user %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <!--<li><%# link_to "Inbox", mailbox_inbox_path %></li>-->
            <li class="divider"></li>
            <li><%= link_to "My Questions", questions_path %></li>
            <li><%= link_to "My Work", works_path %></li>
            <li><a href="#">Knowledge Base</a></li>
            <li><%= link_to "Post a Project", new_project_path %></li>
            <li class="divider"></li>
            <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_slide_show.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag "slide-1-final.jpg" %>
    </div>
    <div class="item">
      <%= image_tag "slide-2-final.jpg" %>
    </div>
    <div class="item">
      <%= image_tag "slide-3-final.jpg" %>
    </div>
    
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tradesgram</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <%= render 'layouts/registered_user_nav' %>
<% else %>
  <%= render 'layouts/non_user_nav' %>
<% end %>


<% flash.each do |type, content| %>
    <% if content.respond_to?('each') 
        content.each do |item| %>
            <%= render 'layouts/alert', 
                type: type,
                content: item %>
        <% end %>
    <% else %>
        <%= render 'layouts/alert', 
                type: type,
                content: content %>
    <% end %>
<% end %>
<div class="container">
	<%= yield %>
</div><!-- end container -->
<%= render 'layouts/footer' %>
</body>
</html>